### ISSUE TITLE
without headers

### ISSUE THREAD

**Issue by hasan-ahani** [hossein-zare/wester-chunk-upload#1]
سلام وقت شما بخیر
ممنون بابت این پکیج کاربردی
من 2 تا مورد هست که مشکل دارم.

اول اینکه چجوری میشه اطلاعات header رو از طریق data ست کرد؟
اطلاعات form data:

`chunkNumber: 1
chunkSize: 1048576
currentChunkSize: 606857
totalSize: 606857
identifier: 5646test.zip
filename: test.zip
relativePath: test.zip
totalChunks: 1
file: (binary)`

میخوام ببینم این امکان وجود داره؟

و دوم اینکه گزینه هست که ftp connection که از قبل وجود داره به کلاس بدیم تا نیاز نباشه اطلاعات ورود رو بهش بدیم؟

ممنون

**Comment by hossein-zare** [comment]
سلام.

داده ها فقط با هدر امکان پذیره.
باید توی فایل کانفیگ آرایه ای ایجاد کنید با اطلاعات اف تی پی و هر کجا نیاز بود ازش استفاده کنید.

```php
// config.php
$ftp_credentials = [
    'server' => '',
    'username' => '',
    'password' => '',
];
```

```php
// upload.php
require_once("config.php");

$chunk = new Chunk([
...
    'driver' => 'ftp',
    'ftp_driver' => [
        ...$ftp_credentials,

        'path' =>  '/uploads/',
        'tmp_path' => '/uploads/temp/',
    ],
...
]);
