### ISSUE TITLE
Setting headers doesn't work

### ISSUE THREAD

**Issue by inari6735** [hossein-zare/wester-chunk-upload#2]
I tried to implement this library as solution for upload big files in my project. On every request there is 400 status code and "The data is invalid" response message. I tried to debug and below is what i found:

1. When i post a file via the request with proper headers i can easly print them out by built in php getallheaders() function
![image](https://user-images.githubusercontent.com/32057515/191245994-853c5f90-36e1-42ad-b7bd-86174a88efb6.png)
![image](https://user-images.githubusercontent.com/32057515/191247346-3d610a7c-33c1-471f-b772-9eefca9e3f5a.png)

2. But when i try to create new object of class Chunk() from your library there is a step where headers are setting up. Inside the Header.php file there is setHeaders() function that calls getallheaders(), but there this function returns an empty array. 
![image](https://user-images.githubusercontent.com/32057515/191246559-3ec3e836-5e17-487e-9473-85e22bd03937.png)

3. The validate method inside Validator.php checks the headers, but there are not set up headers from request and the ValidationException is thrown with "The data is invalid" message.

**Comment by hossein-zare** [comment]
What validation rules are you using?

Example:
```php
'validation' => ['extension:mp4,avi'],
```

Please test your project using XAMPP, I tested the library and it works.

**Comment by gitbugr** [comment]
This was an issue for me also, am using nginx + php-fpm. 
Headers are case-insensitive, and commonly capitalised, but you're using a case-sensitive check with lowercase keys. Fixed in my PR #3
