### ISSUE TITLE
Why does isChunk() check like this? It seems impossible to determine through this check.

### ISSUE THREAD

**Issue by wf58585858** [hossein-zare/wester-chunk-upload#6]
```
private function isChunk(): bool
{
    return $this->file->name === 'blob'
        && $this->file->type === 'application/octet-stream';
}
```
Why do we need to check if the name is 'blob'? I have the original name of the file I uploaded here, so I cannot determine it through this check.

**Comment by hossein-zare** [comment]
Each file needs to be sliced into chunks and then sent to the server. Consider implementing the client-side correctly.

Please see https://github.com/hossein-zare/wester-chunk-upload-examples/blob/27a70577433f437aec18bb1992622498dae837a3/javascript/chunk.js#L43C53-L43C53

Javascript Example (Client-Side): https://github.com/hossein-zare/wester-chunk-upload-examples/tree/master/javascript
