### ISSUE TITLE
Error on setDriver function

### ISSUE THREAD

**Issue by anicauli** [hossein-zare/wester-chunk-upload#7]
THe setDriver function must be like:

    private function setDriver()
    {
        if (in_array($this->configs['driver'], ['local', 'ftp'])) {
            $name = ucfirst($this->configs['driver']);
            $driver = "\\Wester\\ChunkUpload\\Drivers\\{$name}Driver";
        } else {
            $driver = $this->configs['driver'];
        }

        $this->driver = new $driver($this);
        $this->driver->open();

        return $this;
    }
    
    
    It throws error because $driver is not defined when you use a custom driver

**Comment by hossein-zare** [comment]
Which version of the package are you using? Install the latest version.
